[phases.setup]
nixPkgs = [
    "python311",
    "pipenv",   
    "cairo",
    "pango",
    "gdk-pixbuf",
    "gobject-introspection",
    "libffi"
]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install -r requirements.txt"
]