[phases.setup]
nixPkgs = [ 
    "python311Full",
    "cairo",
    "pango",
    "gdk-pixbuf",
    "gobject-introspection",
    "libffi"
]

[phases.install]
cmds = [
    "curl -O https://bootstrap.pypa.io/get-pip.py",
    "python3.11 get-pip.py",
    "python3.11 -m pip install --upgrade setuptools",
    "python3.11 -m pip install -r requirements.txt"
]

