[phases.setup]
nixPkgs = [
    "python311",
    "python311Packages.pip",
    "cairo",
    "pango",
    "gdk-pixbuf",
    "gobject-introspection",
    "libffi",
    "gcc",
    "pkg-config"
]

[phases.install]
cmds = [
    "python -m pip install --upgrade pip",
    "python -m pip install -r requirements.txt"
]

[start]
cmd = "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn comite_pro.wsgi"