[phases.setup]
nixPkgs = [ 
    "cairo",
    "pango",
    "gdk-pixbuf",
    "gobject-introspection",
    "libffi",
    { name = "python", value = "python311.withPackages (ps: with ps; [ pip setuptools wheel ])" }
]

[phases.install]
cmds = [
    "pip install -r requirements.txt"
]

