[phases.setup]
nixPkgs = [
    "python311",
    "cairo",
    "pango",
    "gdk-pixbuf",
    "gobject-introspection",
    "libffi",
    "gcc",
    "pkg-config"
]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install -r requirements.txt"
]

