[phases.setup]
nixPkgs = [
  "python311",
  "python311Packages.pip",
  "python311Packages.setuptools",
  "python311Packages.wheel",

  "cairo",
  "pango",
  "gdk-pixbuf",
  "gobject-introspection",
  "libffi",
  "glib",
  "harfbuzz",
  "fontconfig",
  "freetype",
  "brotli",
  "zlib",
  "pkg-config",
  "gcc",

  "python311Packages.django",
  "python311Packages.psycopg2",
  "python311Packages.numpy",
  "python311Packages.pandas",
  "python311Packages.openpyxl",
  "python311Packages.python-dateutil",
  "python311Packages.python-dotenv",
  "python311Packages.sqlparse",
  "python311Packages.pillow",
  "python311Packages.whitenoise",
  "python311Packages.cffi",
  "python311Packages.crispy_forms",
  "python311Packages.setuptools",
  "python311Packages.pygments",
  "python311Packages.traitlets",
  "python311Packages.typing-extensions"
]

[phases.install]
cmds = [

]

[start]
cmd = "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn comite_pro.wsgi"