[phases.setup]
nixPkgs = [ 
    "python311Full",
    "cairo",
    "pango",
    "gdk-pixbuf",
    "gobject-introspection",
    "libffi"
]

[phases.install]
cmds = [
    "python3.11 -m ensurepip",
    "python3.11 -m pip install --upgrade pip",
    "python3.11 -m pip install -r requirements.txt"
]