# Generated by Django 5.1.2 on 2024-10-15 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0004_alter_empresa_razon_social'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoCuentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('tipo', models.CharField(choices=[('Activo', 'Activo'), ('Pasivo', 'Pasivo'), ('Capital', 'Capital'), ('Ingreso', 'Ingreso'), ('Egreso', 'Egreso')], max_length=10, verbose_name='tipo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogos', to='empresa.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='código')),
                ('saldo', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='saldo')),
                ('nivel', models.PositiveIntegerField(default=1, verbose_name='nivel')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('catalogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas', to='catalogo_cuentas.catalogocuentas')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcuentas', to='catalogo_cuentas.cuenta')),
            ],
        ),
    ]
