# Generated by Django 5.1.2 on 2025-06-05 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogocuentas',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si está activo en el sistema', verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si está activa en el sistema', verbose_name='Activo'),
        ),
    ]
