# Generated by Django 5.1.2 on 2024-10-30 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doccomprobante',
            name='numero_documento',
            field=models.CharField(max_length=50, unique=True, verbose_name='Documento'),
        ),
    ]
