# Generated by Django 5.1.2 on 2024-10-30 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_alter_doccomprobante_numero_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doccomprobante',
            name='serie_documento',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Serie'),
        ),
    ]
