# Generated by Django 5.1.2 on 2025-05-05 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0003_alter_doccomprobante_serie_documento'),
        ('terceros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doccomprobante',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comprobantes', to='terceros.cliente', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='doccomprobante',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comprobantes', to='terceros.proveedor', verbose_name='Proveedor'),
        ),
    ]
