# Generated by Django 5.1.2 on 2025-05-13 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0004_doccomprobante_cliente_doccomprobante_proveedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doccomprobante',
            name='cliente',
        ),
    ]
