# Generated by Django 5.1.2 on 2025-05-13 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0005_remove_doccomprobante_cliente'),
        ('terceros', '0002_remove_donante_empresa_persona_delete_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doccomprobante',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comprobantes', to='terceros.persona', verbose_name='Cliente'),
        ),
    ]
