# Generated by Django 5.1.2 on 2025-06-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0007_doccomprobante_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipodocumento',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si está activo en el sistema', verbose_name='Activo'),
        ),
    ]
