"""
Django settings for comite_pro project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
import dj_database_url
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-ee39cq+k96v1j!$+bvg1fzx!%97vttz*avyt3y2@wd3+d=xew&')

# SECURITY WARNING: don't run with debug turned on in production!
# Detectar entorno
IS_PRODUCTION = os.getenv('RAILWAY_ENVIRONMENT') is not None
DEBUG = os.getenv('DEBUG', 'False').lower() == 'true' if IS_PRODUCTION else True

# Configuración de hosts permitidos
ALLOWED_HOSTS = []
if IS_PRODUCTION:
    ALLOWED_HOSTS = [
        '.railway.app',
        'comitepro-production.up.railway.app',
        os.getenv('RAILWAY_STATIC_URL', '').replace('https://', ''),
    ]
else:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1']

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# Database - SIEMPRE usar Railway
DATABASES = {
    'default': dj_database_url.config(
        default=os.getenv('DATABASE_URL'),
        conn_max_age=600,
        conn_health_checks=True,
    )
}

# Configuración adicional para Railway con timeouts extendidos (solo opciones válidas)
""" if DATABASES['default'] and not IS_PRODUCTION:
    DATABASES['default'].update({
        'OPTIONS': {
            'connect_timeout': 30,
            'sslmode': 'require',
        }
    })
 """
# Fix para dbshell con Railway
if not IS_PRODUCTION:
    db_from_env = dj_database_url.parse(os.getenv('DATABASE_URL'))
    if db_from_env:
        DATABASES['default'].update(db_from_env)

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'whitenoise.runserver_nostatic',
    'crispy_forms',
    'crispy_tailwind',
    'django_extensions',
    'empresa',
    'usuarios',
    'catalogo_cuentas',
    'documentos',
    'transacciones',
    'bancos',
    'reportes',
    'terceros'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'comite_pro.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'comite_pro.wsgi.application'

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'es-gt'
TIME_ZONE = 'America/Guatemala'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
MEDIA_URL = '/media/'          # URL para acceder a los archivos en el navegador
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  # Ruta donde se guardan los archivos


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

# WhiteNoise configuration
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Crispy Forms
CRISPY_ALLOWED_TEMPLATE_PACKS = "tailwind"
CRISPY_TEMPLATE_PACK = "tailwind"

# Auth redirects
LOGOUT_REDIRECT_URL = '/usuarios/login/'
LOGIN_REDIRECT_URL = '/empresa/'
LOGIN_URL = '/usuarios/login/'

ADMIN_VERIFICATION_KEY = "ADM1N_S3CUR3"  

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Security settings for production
if IS_PRODUCTION:
    SECURE_SSL_REDIRECT = False # Railway maneja HTTPS, no forzar redirección
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# CSRF settings
CSRF_TRUSTED_ORIGINS = [
    'https://comitepro-production.up.railway.app',
    'https://*.railway.app',
]
