# Generated by Django 5.1.2 on 2024-10-21 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo_cuentas', '0001_initial'),
        ('documentos', '0001_initial'),
        ('empresa', '0004_alter_empresa_razon_social'),
        ('transacciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoBanco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.CharField(max_length=50, verbose_name='Número del Documento:')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='documentos_banco', to='catalogo_cuentas.cuenta')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_banco', to='empresa.empresa')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='documentos_banco', to='documentos.tipodocumento')),
                ('transaccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_banco', to='transacciones.transaccion')),
            ],
        ),
    ]
