# Generated by Django 5.1.2 on 2024-10-21 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bancos', '0002_alter_documentobanco_tipo_documento'),
        ('documentos', '0001_initial'),
        ('transacciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentobanco',
            name='tipo_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='documentos_banco', to='documentos.tipodocumento'),
        ),
        migrations.AlterField(
            model_name='documentobanco',
            name='transaccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos_banco', to='transacciones.transaccion'),
        ),
    ]
