# Generated by Django 5.1.2 on 2024-10-30 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bancos', '0004_remove_documentobanco_cuenta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentobanco',
            name='transaccion',
        ),
    ]
