# Generated by Django 5.1.2 on 2024-10-30 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bancos', '0005_remove_documentobanco_transaccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentobanco',
            name='numero_documento',
            field=models.CharField(max_length=50, unique=True, verbose_name='Número del Documento:'),
        ),
    ]
