# Generated by Django 5.1.2 on 2025-05-05 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bancos', '0008_alter_documentobanco_numero_documento'),
        ('terceros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentobanco',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_banco', to='terceros.cliente', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='documentobanco',
            name='donante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_banco', to='terceros.donante', verbose_name='Donante'),
        ),
    ]
