# Generated by Django 5.1.2 on 2025-05-13 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bancos', '0009_documentobanco_cliente_documentobanco_donante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentobanco',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='documentobanco',
            name='donante',
        ),
    ]
