# Generated by Django 5.1.2 on 2025-05-13 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bancos', '0010_remove_documentobanco_cliente_and_more'),
        ('terceros', '0002_remove_donante_empresa_persona_delete_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentobanco',
            name='Entidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_banco', to='terceros.persona', verbose_name='Entidad'),
        ),
        migrations.AddField(
            model_name='documentobanco',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_banco', to='terceros.proveedor', verbose_name='Proveedor'),
        ),
    ]
