# Generated by Django 5.1.2 on 2025-05-17 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bancos', '0011_documentobanco_entidad_documentobanco_proveedor'),
        ('documentos', '0006_doccomprobante_cliente'),
        ('empresa', '0007_alter_empresa_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentobanco',
            old_name='Entidad',
            new_name='entidad',
        ),
        migrations.AlterField(
            model_name='documentobanco',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_banco', to='empresa.empresa', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='documentobanco',
            name='tipo_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='documentos_banco', to='documentos.tipodocumento', verbose_name='Tipo de Documento'),
        ),
    ]
