# Generated by Django 5.1.2 on 2025-05-28 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bancos', '0012_rename_entidad_documentobanco_entidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentobanco',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si el documento está activo en el sistema', verbose_name='Activo'),
        ),
    ]
