# Generated by Django 5.1.2 on 2024-10-18 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo_cuentas', '0001_initial'),
        ('documentos', '0001_initial'),
        ('empresa', '0004_alter_empresa_razon_social'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto')),
                ('tipo_transaccion', models.CharField(choices=[('Ingreso', 'Ingreso'), ('Egreso', 'Egreso')], max_length=10)),
                ('tipo_operacion', models.CharField(choices=[('Transacción', 'Transacción'), ('Póliza', 'Póliza')], default='Transacción', max_length=15)),
                ('numero_poliza', models.PositiveIntegerField(blank=True, null=True, verbose_name='Poliza')),
                ('comprobante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='documentos.doccomprobante')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='empresa.empresa')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='empresa.periodocontable')),
                ('tipo_documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documentos.tipodocumento')),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debe', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True)),
                ('haber', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='catalogo_cuentas.cuenta')),
                ('transaccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='transacciones.transaccion')),
            ],
        ),
    ]
