# Generated by Django 5.1.2 on 2024-11-03 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0002_transaccion_banco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='monto_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='tipo_transaccion',
            field=models.CharField(blank=True, choices=[('Ingreso', 'Ingreso'), ('Egreso', 'Egreso')], max_length=10, null=True),
        ),
    ]
