# Generated by Django 5.1.2 on 2025-05-29 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0003_alter_transaccion_monto_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si la póliza está activa en el sistema', verbose_name='Activo'),
        ),
    ]
