# Generated by Django 5.1.2 on 2025-05-13 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bancos', '0010_remove_documentobanco_cliente_and_more'),
        ('documentos', '0005_remove_doccomprobante_cliente'),
        ('empresa', '0007_alter_empresa_usuario'),
        ('terceros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donante',
            name='empresa',
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Correo Electrónico')),
                ('tipo', models.CharField(choices=[('CL', 'Cliente'), ('DO', 'Donante')], max_length=2, verbose_name='Tipo de Persona')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personas', to='empresa.empresa')),
            ],
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Donante',
        ),
    ]
