# Generated by Django 5.1.2 on 2025-06-05 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0002_remove_donante_empresa_persona_delete_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si está activo en el sistema', verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si está activo en el sistema', verbose_name='Activo'),
        ),
    ]
