# Generated by Django 5.1.2 on 2024-10-10 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rtu', models.CharField(max_length=15, unique=True, verbose_name='rtu')),
                ('razon_social', models.CharField(max_length=200, unique=True, verbose_name='razón social')),
                ('giro', models.CharField(max_length=200, verbose_name='giro')),
                ('direccion', models.CharField(max_length=300, verbose_name='dirección')),
                ('telefono', models.CharField(max_length=20, verbose_name='teléfono')),
            ],
        ),
    ]
