# Generated by Django 5.1.2 on 2024-10-11 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='razon_social',
            field=models.CharField(max_length=200, unique=True, verbose_name='razónsocial'),
        ),
    ]
