# Generated by Django 5.1.2 on 2024-11-01 04:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0006_remove_empresa_usuario_empresa_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='usuario',
            field=models.ManyToManyField(blank=True, related_name='empresa', to=settings.AUTH_USER_MODEL),
        ),
    ]
